language: C++
matrix:
  include:
  - os: osx
    compiler: clang
    osx_image: xcode8.3
before_install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    # https://launchpad.net/~beineri/+archive/ubuntu/opt-qt59-trusty
    sudo add-apt-repository ppa:beineri/opt-qt59-trusty -y &&
    sudo apt-get update -qq
  fi
- |
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update &&
      brew upgrade cmake &&
      brew install qt5 &&
      chmod -R 755 /usr/local/opt/qt5/*
  fi
install:
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get install -qq qt59base &&
      source /opt/qt59/bin/qt59-env.sh
  fi
script:
- mkdir build && cd build
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      cmake .. &&
      cmake --build .
  fi
- |
  if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      cmake -D CMAKE_PREFIX_PATH=$(brew --prefix qt5) .. &&
      make
      $(brew --prefix qt5)/bin/macdeployqt GameHall.app -qmldir=..
      export RELEASE_APP_BUNDLE=$(pwd)/GameHall.app
  fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: PcDxthCrovMTMdrSh1KOB5jxqhW/40zJuNszIUNTZRJbq2QgrMdrelf0So+xW1Gma1YKZlHS7/8TbmD/tipVnzn3lGnDiM8IxPADXgRcpgu/TUVy5K7sstnnSqvJLu3Q4eIrMyvAszNJ6q+Q/pl3QeYT/cXib5XqbeQ0zW9DT9eKd+PeFeZvMHy55P5xlLmY+m6U7ug8ndhu4hXRJrcDWhYp9wQAF3aWsksXy34MxuULgU5D+rpYoh/B49FlbgAs5NQcYSU4lIiGa1E7lFPPCUyzxs+B5ZEepBdCp/RY39vLfUa/2Hs+krHEU7g3Rk5xHkkIRvRDrEnfeMZyZUCCj6KlQ6BNy550DfhezmDBwtodGKmw7qHGN/SoFaol9ZjaD9+hwaBaka+oXi0O5t/qB2v3nYwuHPMtVxKm8600J+8zSn5aIhhdHOLjWfBuWr62nLxyT2uTL7ZjNW6XUlnw48StqYuC7zBjgUDed2CpxCZP2Tgbo/z6XAE1sYeUm7/3XBrCn0RV1uzHwaHujQfvvBpXOGf85tR3fQC0tKeU0qoEFj4ImuH3TwAjkrzFFF8FJ38ElXhmDivdYIoKRW69Mph6Dvx2xpUgheynN54UgwHtgOuR/KCD6sYGtm2ddxbNODSwk6a7CvWzFEfLs7qgwF4SFzsiPY5V6Ore3vhdrsI=
  file: "${RELEASE_APP_BUNDLE}"
  on:
    repo: begoat/GameHall
    branch: william-patch-1
    tags: true
